<?xml version="1.0" ?>
<robot name="arm" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="link0_len" value="0.01" />
    <xacro:property name="link0_rad" value="0.1" />
    <xacro:property name="link1_len" value="0.6" />
    <xacro:property name="link1_width" value="0.05" />
    <xacro:property name="link2_len" value="0.2" />
    <xacro:property name="link2_width" value="0.05" />
    <xacro:property name="link3_len" value="0.2" />
    <xacro:property name="link3_width" value="0.05" />
    <xacro:property name="link4_len" value="0.05" />
    <xacro:property name="link4_width" value="0.05" />
    <xacro:property name="link5_len" value="0.05" />
    <xacro:property name="link5_width" value="0.05" />
    <xacro:property name="gripper_len" value="0.07" />
    <xacro:property name="gripper_rad" value="0.01" />
    <xacro:property name="offset_gripper" value="0.01" />
    <xacro:property name="lim_eff" value="30" />
    <xacro:property name="lim_low" value="-0.78539816339" />
    <xacro:property name="lim_up" value="0.78539816339" />
    <xacro:property name="lim_vel" value="1.571" />

    <xacro:macro name="box_inertia" params="m x y z">
        <inertia ixx="${0.0833333 * m * (y*y + z*z)}" ixy="0.0" ixz="0.0" iyy="${0.0833333 * m * (x*x + z*z)}" iyz="0.0" izz="${0.0833333 * m * (x*x + y*y)}" />
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertia ixx="${ m * ( 3 * r*r + h*h ) / 12}" ixy="0" ixz="0" iyy="${ m * ( 3 * r*r + h*h ) / 12}" iyz="0" izz="${ m * r / 2}" />
    </xacro:macro>

    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>
    <material name="orange">
        <color rgba="1.0 0.4 0.0 1.0"/>
    </material>

    <xacro:macro name="arm" params="parent translateX translateY translateZ">

        <joint name="joint_base" type="revolute">
            <parent link="${parent}"/>
            <child link="link0"/>
            <origin rpy="0 0 0" xyz="${translateX} ${translateY} ${translateZ}"/>
            <axis xyz="0 0 1"/>
            <limit effort="${lim_eff}" lower="${lim_low}" upper="${lim_up}" velocity="${lim_vel}"/>
        </joint>

        <link name="link0">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${link0_len/2}"/>
                <geometry>
                    <cylinder length="${link0_len}" radius="${link0_rad}"/>
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${link0_len/2}"/>
                <geometry>
                    <cylinder length="${link0_len}" radius="${link0_rad}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${link0_len/2}"/>
                <mass value="1"/>
                <cylinder_inertia m="1" r="${link0_rad}" h="${link0_len}" />
            </inertial>
        </link>
        <joint name="joint0" type="revolute">
            <parent link="link0"/>
            <child link="link1"/>
            <origin rpy="0 0 0" xyz="0 0 ${link0_len}"/>
            <axis xyz="0 1 0"/>
            <limit effort="${lim_eff}" lower="${lim_low}" upper="${lim_up}" velocity="${lim_vel}"/>
        </joint>

        <link name="link1">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${link1_len/2}"/>
                <geometry>
                    <box size="${link1_width} ${link1_width} ${link1_len}"/>
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${link1_len/2}"/>
                <geometry>
                    <box size="${link1_width} ${link1_width} ${link1_len}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${link1_len/2}"/>
                <mass value="1"/>
                <box_inertia m="1" x="${link1_width}" y="${link1_width}" z="${link1_len}" />
            </inertial>
        </link>

        <joint name="joint1" type="revolute">
            <parent link="link1"/>
            <child link="link2"/>
            <origin rpy="0 0 0" xyz="0 0 ${link1_len}"/>
            <axis xyz="0 1 0"/>
            <limit effort="${lim_eff}" lower="${lim_low}" upper="${lim_up}" velocity="${lim_vel}"/>
        </joint>

        <link name="link2">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${link2_len/2}"/>
                <geometry>
                    <box size="${link2_width} ${link2_width} ${link2_len}"/>
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${link2_len/2}"/>
                <geometry>
                    <box size="${link2_width} ${link2_width} ${link2_len}"/>
                </geometry>
                <material name="orange"/>
            </visual>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${link2_len/2}"/>
                <mass value="1"/>
                <box_inertia m="1" x="${link2_width}" y="${link2_width}" z="${link2_len}" />
            </inertial>
        </link>

        <joint name="joint2" type="revolute">
            <parent link="link2"/>
            <child link="link3"/>
            <origin rpy="0 0 0" xyz="0 0 ${link2_len}"/>
            <axis xyz="0 0 1"/>
            <limit effort="${lim_eff}" lower="${lim_low}" upper="${lim_up}" velocity="${lim_vel}"/>
        </joint>

        <link name="link3">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${link3_len/2}"/>
                <geometry>
                    <box size="${link3_width} ${link3_width} ${link3_len}"/>
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${link3_len/2}"/>
                <geometry>
                    <box size="${link3_width} ${link3_width} ${link3_len}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${link3_len/2}"/>
                <mass value="1"/>
                <box_inertia m="1" x="${link3_width}" y="${link3_width}" z="${link3_len}" />
            </inertial>
        </link>

        <joint name="joint3" type="revolute">
            <parent link="link3"/>
            <child link="link4"/>
            <origin rpy="0 0 0" xyz="0 0 ${link3_len}"/>
            <axis xyz="0 1 0"/>
            <limit effort="${lim_eff}" lower="${lim_low}" upper="${lim_up}" velocity="${lim_vel}"/>
        </joint>

        <link name="link4">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${link4_len/2}"/>
                <geometry>
                    <box size="${link4_width} ${link4_width} ${link4_len}"/>
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${link4_len/2}"/>
                <geometry>
                    <box size="${link4_width} ${link4_width} ${link4_len}"/>
                </geometry>
                <material name="orange"/>
            </visual>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${link4_len/2}"/>
                <mass value="1"/>
                <box_inertia m="1" x="${link4_width}" y="${link4_width}" z="${link4_len}" />
            </inertial>
        </link>

        <joint name="joint4" type="revolute">
            <parent link="link4"/>
            <child link="link5"/>
            <origin rpy="0 0 0" xyz="0 0 ${link4_len}"/>
            <axis xyz="0 0 1"/>
            <limit effort="${lim_eff}" lower="${lim_low}" upper="${lim_up}" velocity="${lim_vel}"/>
        </joint>

        <link name="link5">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${link5_len/2}"/>
                <geometry>
                    <box size="${link5_width} ${link5_width} ${link5_len}"/>
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${link5_len/2}"/>
                <geometry>
                    <box size="${link5_width} ${link5_width} ${link5_len}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${link5_len/2}"/>
                <mass value="1"/>
                <box_inertia m="1" x="${link5_width}" y="${link5_width}" z="${link5_len}" />
            </inertial>
        </link>

        <joint name="joint5" type="revolute">
            <parent link="link5"/>
            <child link="gripper_left"/>
            <origin rpy="0 0 0" xyz="0 ${offset_gripper} ${link5_len}"/>
            <axis xyz="1 0 0"/>
            <limit effort="${lim_eff}" lower="${lim_low}" upper="${lim_up}" velocity="${lim_vel}"/>
        </joint>

        <joint name="joint6" type="revolute">
            <parent link="link5"/>
            <child link="gripper_right"/>
            <origin rpy="0 0 0" xyz="0 -${offset_gripper} ${link5_len}"/>
            <axis xyz="1 0 0"/>
            <limit effort="${lim_eff}" lower="${lim_low}" upper="${lim_up}" velocity="${lim_vel}"/>
        </joint>

        <link name="gripper_left">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${gripper_len/2}"/>
                <geometry>
                    <cylinder length="${gripper_len}" radius="${gripper_rad}"/>
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${gripper_len/2}"/>
                <geometry>
                    <cylinder length="${gripper_len}" radius="${gripper_rad}"/>
                </geometry>
                <material name="orange"/>
            </visual>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${gripper_len/2}"/>
                <mass value="1"/>
                <cylinder_inertia m="1" r="${gripper_rad}" h="${gripper_len}" />
            </inertial>
        </link>

        <link name="gripper_right">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${gripper_len/2}"/>
                <geometry>
                    <cylinder length="${gripper_len}" radius="${gripper_rad}"/>
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${gripper_len/2}"/>
                <geometry>
                    <cylinder length="${gripper_len}" radius="${gripper_rad}"/>
                </geometry>
                <material name="orange"/>
            </visual>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${gripper_len/2}"/>
                <mass value="1"/>
                <cylinder_inertia m="1" r="${gripper_rad}" h="${gripper_len}" />
            </inertial>
        </link>
        <!-- Transmission is important to link the joint and the controller -->

        <!--
        <transmission name="joint_base_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="joint_base">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="joint_base_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="joint0_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="joint0">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="joint0_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="joint1_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="joint1">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="joint1_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="joint2_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="joint2">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="joint2_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="joint3_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="joint3">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="joint3_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="joint4_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="joint4">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="joint4_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="joint5_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="joint5">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="joint5_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="joint6_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="joint6">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="joint6_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
        -->
    </xacro:macro>

</robot>
